import React, { useState } from 'react';
import Footer from '../Footer';

const CentralMonitoring = () => {
  const bubbleData = [
    [{ color: 'bg-black' }, { color: 'bg-red-500' }, { color: 'bg-black' }],
    [{ color: 'bg-black' }, { color: 'bg-black' }],
    [{ color: 'bg-red-500' }],
  ];
  const [isModalOpen, setModalOpen] = useState(false);

  const openModal = () => setModalOpen(true);
  const closeModal = () => setModalOpen(false);

  return (
    // main div
    <div className="w-[1535px]">
      {/* home div */}
      <div className="w-full h-[450px]">
        <img
          src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
          alt="not found img"
          className="w-full h-full object-cover opacity-80 z-50"
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <div className="text-bold text-black text-center px-4 py-1 z-10 ">
            <h1 className="text-5xl font-bold">Central Monitoring</h1>
            <p className="text-2xl font-bold pt-3">
              Worried about the security of your premises when you are away?
              <br />
              Don't worry! Get your site monitored 24 X 7 by our Alert and
              Vigilant Monitoring Team!
            </p>
          </div>
        </div>
      </div>
      {/* 2nd div */}
      <div className="w-full h-[416px] flex ">
        {/* inner div */}
        <div className="w-[1200px] gap-5 flex items-center mx-auto">
          {/* 1st div */}
          <div className="w-[600px] h-[366px] flex items-center ">
            {/* bubble div */}
            <div className="w-[570px] h-[132px] flex items-center justify-center">
              <div className="flex flex-col items-end mt-[-3rem] mr-3 gap-1 ">
                {bubbleData.map((line, index) => (
                  <div key={index} className="flex justify-center gap-1">
                    {line.map((bubble, i) => (
                      <div
                        key={i}
                        className={`${bubble.color} w-3 h-3 flex items-center justify-center rounded-full`}
                      ></div>
                    ))}
                  </div>
                ))}
              </div>
              {/* text */}
              <p className="text-4xl font-bold">
                Get your site monitored <br /> 24X7 by our Alert & Vigilant{' '}
                <br /> Monitoring Team!
              </p>
            </div>
          </div>
          {/* 2nd div */}
          <div className="w-[570px] h-[366px] flex flex-col pt-8 gap-4">
            <p className="text-lg font-serif">
              Central Monitoring is a security, surveillance and operational
              monitoring service for homes, retail outlets, banks, educational
              institutions, warehouses, industrial units, offices, vehicles and
              any other form of residential or business establishment.
            </p>
            <p className="text-lg font-serif">
              We also host a state-of-the-art command center for the alert based
              and scheduled monitoring of the sites. We promote our monitoring
              services under the brand name iMONITOR India and have several
              service products to monitor alerts generated by intruder alarm
              systems, fire alarm systems, CCTV surveillance systems and guard
              monitoring systems.
            </p>
          </div>
        </div>
      </div>
      {/* work div */}
      <div className="w-full h-[476px] px-[10rem] grid grid-cols-2 bg-gray-200">
        {/* paragraph div */}
        <div className="w-[595px] h-[466px] flex flex-col py-4 ">
          <h1 className="w-[300px] h-[50px] font-serif font-bold text-4xl">
            How It Works
          </h1>
          <p className="w-[590px] h-[173px] text-lg font-thin">
            Intelligent devices and sensors installed at the customer’s premises
            can identify an intrusion, fire, panic alarm, medical alarm,
            unauthorized access, vehicle route deviation etc. and send an alert
            to our central monitoring station. Upon receiving an alert, our
            monitoring officers study the alert information received and monitor
            live video and audio from the customer’s site.
          </p>
          <p className="w-[575px] h-[180px] text-lg font-thin">
            If necessary, they call the customer for verification. Then our
            monitoring officers take appropriate action and inform the customers
            emergency contacts by phone, SMS and email. We can also call the
            police, fire brigade and medical emergency services. Meanwhile,
            crime can be deterred via 2 way audio communication through a mic &
            speaker at the site We will stay in touch with the customer till the
            incident is resolved, documented and finally closed.
          </p>
        </div>
        <div className="w-[595px] h-[466px] py-4 grid">
          <h1 className="w-[570px] h-[4px] font-serif text-center font-bold text-4xl">
            Our Command Center
          </h1>
          <div className="grid grid-cols-3 gap-3 py-0 w-[545px] h-[240px]">
            {/* first image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/1.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/1.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* 2nd image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/1.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* 3rd image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/3.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* 4th image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/4.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* 5th image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/5.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* 6th image */}
            <div>
              {/* Image with hover effect */}
              <div className="relative w-[178px] h-[118px] group">
                {/* Image */}
                <img
                  src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/6.jpg"
                  alt="Thumbnail"
                  className="w-full h-full object-cover"
                />

                {/* Hover Overlay */}
                <div
                  className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 cursor-pointer"
                  onClick={openModal}
                >
                  {/* Search Icon */}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 4a7 7 0 100 14 7 7 0 000-14zm0 0l7 7"
                    />
                  </svg>
                </div>
              </div>

              {/* Modal */}
              {isModalOpen && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
                  <div className="relative">
                    {/* Large Image */}
                    <img
                      src="https://www.securicoelectronics.com/wp-content/uploads/2020/11/2.jpg"
                      alt="Large View"
                      className="w-[90vw] max-w-[800px] h-auto rounded"
                    />
                    {/* Close Button */}
                    <button
                      className="absolute top-2 right-2 text-white text-2xl font-bold"
                      onClick={closeModal}
                    >
                      &times;
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default CentralMonitoring;
